# Generated by Django 2.2.1 on 2019-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appversiontable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versioncode', models.IntegerField(default=0)),
                ('versionname', models.FloatField(default=0)),
                ('describe', models.CharField(max_length=500)),
                ('updatetime', models.FloatField(default=1557483607.000735)),
                ('downloadlink', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Broadcasttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casttime', models.FloatField(default=1557483607.0010548)),
                ('servicestatus', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donatetable',
            fields=[
                ('donatetime', models.FloatField(default=1557483607.0013795, primary_key=True, serialize=False)),
                ('donator', models.CharField(max_length=20)),
                ('donatetype', models.CharField(default='Money', max_length=10)),
                ('describe', models.CharField(max_length=50)),
                ('message', models.CharField(default='这位是个低调的捐献者!', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Errotable',
            fields=[
                ('errotype', models.CharField(db_index=True, max_length=20)),
                ('errotime', models.FloatField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=2000)),
                ('sendmail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Etable',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('system', models.CharField(max_length=30)),
                ('Model', models.CharField(default='', max_length=20)),
                ('engineposition', models.CharField(max_length=50)),
                ('provider', models.CharField(default='', max_length=20)),
                ('cpu', models.CharField(default='', max_length=20)),
                ('cpufrom', models.CharField(default='', max_length=20)),
                ('memory', models.CharField(default='', max_length=20)),
                ('memoryfrom', models.CharField(default='', max_length=20)),
                ('storage', models.CharField(default='', max_length=20)),
                ('storagefrom', models.CharField(default='', max_length=20)),
                ('power', models.CharField(default='', max_length=20)),
                ('powerfrom', models.CharField(default='', max_length=20)),
                ('motherboard', models.CharField(default='', max_length=20)),
                ('motherboardfrom', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacktable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=1557483606.9996555)),
                ('messagefrom', models.CharField(default='unknow', max_length=20)),
                ('mail', models.EmailField(default='resdig@qq.com', max_length=254)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Keywordtable',
            fields=[
                ('keyword', models.CharField(db_index=True, max_length=90, primary_key=True, serialize=False)),
                ('hot', models.IntegerField(default=1)),
                ('cantfind', models.BooleanField(default=False)),
                ('lastdigtime', models.FloatField(default=1557483606.9987266)),
            ],
        ),
        migrations.CreateModel(
            name='Messagetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=1557483607.0000427)),
                ('messagefrom', models.CharField(default='unknow', max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resourcetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=90)),
                ('link', models.CharField(max_length=800)),
                ('web', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=200, null=True)),
                ('filesize', models.FloatField(default=0)),
                ('scantime', models.FloatField(default=1557483606.9983287)),
            ],
        ),
    ]
