# Generated by Django 3.0.3 on 2020-02-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=True)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('time', models.FloatField(default=1582278466.6200814, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(default='Money', max_length=100)),
                ('msg', models.CharField(default='这位是个低调的捐献者!', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('system', models.CharField(max_length=30)),
                ('model', models.CharField(default='', max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('provider', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(db_index=True, max_length=90, primary_key=True, serialize=False)),
                ('showInRec', models.BooleanField(default=True)),
                ('digTimes', models.IntegerField(default=0)),
                ('lastDigTime', models.FloatField(default=1582278466.6191058)),
            ],
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=800)),
                ('web', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=200, null=True)),
                ('filesize', models.FloatField(default=0)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resdig.Keyword')),
            ],
        ),
        migrations.DeleteModel(
            name='Appversiontable',
        ),
        migrations.DeleteModel(
            name='Broadcasttable',
        ),
        migrations.DeleteModel(
            name='Donatetable',
        ),
        migrations.DeleteModel(
            name='Errotable',
        ),
        migrations.DeleteModel(
            name='Etable',
        ),
        migrations.DeleteModel(
            name='Feedbacktable',
        ),
        migrations.DeleteModel(
            name='Keywordtable',
        ),
        migrations.DeleteModel(
            name='Messagetable',
        ),
        migrations.DeleteModel(
            name='Resourcetable',
        ),
    ]
