# Generated by Django 2.2.1 on 2019-05-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversiontable',
            name='updatetime',
            field=models.FloatField(default=1557547107.7877748),
        ),
        migrations.AlterField(
            model_name='broadcasttable',
            name='casttime',
            field=models.FloatField(default=1557547107.7880132),
        ),
        migrations.AlterField(
            model_name='donatetable',
            name='donatetime',
            field=models.FloatField(default=1557547107.7882495, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='time',
            field=models.FloatField(default=1557547107.7869291),
        ),
        migrations.AlterField(
            model_name='keywordtable',
            name='lastdigtime',
            field=models.FloatField(default=1557547107.7862334),
        ),
        migrations.AlterField(
            model_name='messagetable',
            name='time',
            field=models.FloatField(default=1557547107.7872674),
        ),
        migrations.AlterField(
            model_name='resourcetable',
            name='scantime',
            field=models.FloatField(default=1557547107.785901),
        ),
    ]
