# Generated by Django 2.2.2 on 2019-12-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0003_auto_20191126_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('time', models.FloatField(default=1575810658.9187388, primary_key=True, serialize=False)),
                ('donator', models.CharField(max_length=20)),
                ('info', models.CharField(default='Money', max_length=100)),
                ('message', models.CharField(default='这位是个低调的捐献者!', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('system', models.CharField(max_length=30)),
                ('model', models.CharField(default='', max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('provider', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=1575810658.9180827)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(db_index=True, max_length=90, primary_key=True, serialize=False)),
                ('DBId', models.CharField(default=None, max_length=50)),
                ('digTimes', models.IntegerField(default=1)),
                ('LastDigTime', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=1575810658.918307)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=800)),
                ('web', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=200, null=True)),
                ('filesize', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Appversiontable',
        ),
        migrations.DeleteModel(
            name='Broadcasttable',
        ),
        migrations.DeleteModel(
            name='Donatetable',
        ),
        migrations.DeleteModel(
            name='Etable',
        ),
        migrations.DeleteModel(
            name='Feedbacktable',
        ),
        migrations.DeleteModel(
            name='Keywordtable',
        ),
        migrations.DeleteModel(
            name='Messagetable',
        ),
        migrations.DeleteModel(
            name='Resourcetable',
        ),
        migrations.AddField(
            model_name='keyword',
            name='ress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resdig.Res'),
        ),
    ]
