# Generated by Django 2.2.2 on 2019-12-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0004_auto_20191208_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='DBId',
            new_name='dbId',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='LastDigTime',
            new_name='lastDigTime',
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575810755.772295, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575810755.7715595),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575810755.771809),
        ),
    ]
