# Generated by Django 3.0.3 on 2020-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0004_auto_20200221_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='lastVisitTime',
            field=models.FloatField(default=1582278628.0665753),
        ),
        migrations.AddField(
            model_name='keyword',
            name='visitTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1582278628.0679867, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1582278628.0665607),
        ),
    ]
