# Generated by Django 3.0.3 on 2020-02-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0006_auto_20200221_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1582303851.0266833, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1582303851.0256138),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastVisitTime',
            field=models.FloatField(default=1582303851.0256312),
        ),
    ]
