# Generated by Django 3.0.3 on 2020-02-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0007_auto_20200221_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1582304407.1368423, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1582304407.1358387),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastVisitTime',
            field=models.FloatField(default=1582304407.1358538),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='visitTimes',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
