# Generated by Django 3.0.3 on 2020-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0008_auto_20200221_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1582304937.5883384, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1582304937.586865),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastVisitTime',
            field=models.FloatField(default=1582304937.5868416),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='visitTimes',
            field=models.IntegerField(default=0),
        ),
    ]
