# Generated by Django 2.2.2 on 2019-12-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0009_auto_20191208_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='message',
            new_name='info',
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575810993.7668846, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575810993.7661974),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575810993.766429),
        ),
    ]
