# Generated by Django 3.0.3 on 2020-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0009_auto_20200221_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1582304944.9945657, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1582304944.9935455),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastVisitTime',
            field=models.FloatField(default=1582304944.99353),
        ),
    ]
