# Generated by Django 2.2.2 on 2019-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0010_auto_20191208_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='message',
        ),
        migrations.AddField(
            model_name='donate',
            name='msg',
            field=models.CharField(default='这位是个低调的捐献者!', max_length=100),
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575811077.331839, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575811077.331185),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575811077.3314097),
        ),
    ]
