# Generated by Django 2.2.2 on 2019-12-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0011_auto_20191208_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575813467.9207342, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575813467.9200623),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575813467.9202833),
        ),
    ]
