# Generated by Django 3.0.3 on 2020-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0011_auto_20200221_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1582305385.3733764, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1582305385.3722954),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastVisitTime',
            field=models.FloatField(default=1582305385.3723123),
        ),
    ]
