# Generated by Django 2.2.2 on 2019-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0012_auto_20191208_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575813506.0944028, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575813506.0937245),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575813506.0939586),
        ),
    ]
