# Generated by Django 3.0.3 on 2020-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0012_auto_20200221_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1582310200.5545413, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1582310200.5535238),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastVisitTime',
            field=models.FloatField(default=1582310200.5535388),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='visitTimes',
            field=models.IntegerField(default=0),
        ),
    ]
