# Generated by Django 2.2.2 on 2019-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0013_auto_20191208_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575813529.1719263, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575813529.1710386),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575813529.171334),
        ),
    ]
