# Generated by Django 2.2.2 on 2019-12-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0015_auto_20191208_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575821775.2289162, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575821775.228245),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='dbId',
            field=models.IntegerField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575821775.2284691),
        ),
    ]
