# Generated by Django 2.2.2 on 2019-12-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0018_auto_20191208_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575822295.3357787, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575822295.3350663),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='ress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resdig.Res'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575822295.3353322),
        ),
    ]
