# Generated by Django 2.2.2 on 2019-12-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0019_auto_20191208_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='ress',
        ),
        migrations.AddField(
            model_name='res',
            name='keyword',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resdig.Keyword'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575823398.1200473, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575823398.119362),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575823398.1195948),
        ),
    ]
