# Generated by Django 2.2.2 on 2019-12-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0020_auto_20191208_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575825229.4001102, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575825229.3994396),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575825229.399664),
        ),
        migrations.AlterField(
            model_name='res',
            name='keyword',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='resdig.Keyword'),
            preserve_default=False,
        ),
    ]
