# Generated by Django 2.2.2 on 2019-12-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0021_auto_20191208_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.FloatField(default=1575825285.6795647, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1575825285.6787941),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1575825285.6790555),
        ),
    ]
