# Generated by Django 2.2.2 on 2019-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0022_auto_20191208_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('time', models.FloatField(default=1576337026.1821845, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(default='Money', max_length=100)),
                ('msg', models.CharField(default='这位是个低调的捐献者!', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1576337026.1812963),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1576337026.1815944),
        ),
    ]
