# Generated by Django 3.0.2 on 2020-01-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0024_auto_20191214_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1578714822.8293514, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='info',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.FloatField(default=1578714822.8278334),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1578714822.8259797),
        ),
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.FloatField(default=1578714822.8283565),
        ),
    ]
