# Generated by Django 3.0.2 on 2020-01-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0028_auto_20200111_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='dbId',
        ),
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1578718155.2921581, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1578718155.2907188),
        ),
    ]
