# Generated by Django 3.0.2 on 2020-01-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0029_auto_20200111_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='showInRec',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1578721272.673578, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1578721272.6720655),
        ),
    ]
