# Generated by Django 3.0.2 on 2020-01-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdig', '0030_auto_20200111_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='time',
            field=models.FloatField(default=1578732227.454967, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lastDigTime',
            field=models.FloatField(default=1578732227.4538875),
        ),
    ]
