#!/bin/bash
echo '---------------------------------------'

echo 'kill manager-x...'
ps -ef | grep manager-x | grep -v grep | awk '{print $2}' | xargs kill -9
echo 'done.'

echo 'kill gunicorn...'
ps -ef | grep gunicorn | grep -v grep | awk '{print $2}' | xargs kill -9
echo 'done.'

echo 'kill caddy...'
ps -ef | grep caddy | grep -v grep | awk '{print $2}' | xargs kill -9
echo 'done.'

echo 'starting caddy...'
nohup caddy &
echo 'done.'

echo 'starting gunicorn...'
cd ..
nohup gunicorn -b "127.0.0.1:8000" ocolab.wsgi &
echo 'done.'

echo 'starting manager-x...'
nohup python3 manager-x.py &
echo 'done.'

echo '---------------------------------------'