#!/bin/bash
echo '---------------------------------------'

echo 'kill manager-x...'
ps -ef | grep manager-x | grep -v grep | awk '{print $2}' | xargs kill -9
echo 'done.'

echo 'kill gunicorn...'
ps -ef | grep gunicorn | grep -v grep | awk '{print $2}' | xargs kill -9
echo 'done.'

echo 'kill caddy...'
ps -ef | grep caddy | grep -v grep | awk '{print $2}' | xargs kill -9
echo 'done.'

echo '---------------------------------------'
